name: Docker Image CI

on:
  push:
    branches: [ try-github-actions ]
  pull_request:
    branches: [ try-github-actions ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: my-docker-hub-namespace/my-docker-hub-repository
        tag_with_ref: true
