name: Docker Image CI

on:
  push:
    branches: [ try-github-actions ]
  pull_request:
    branches: [ try-github-actions ]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./.devcontainer/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: lcenchew/dev-container-java/dev-container-java
          tag_with_ref: true
